[theme]
base = "light"             # Fuerza el modo claro
primaryColor = "#0033A0"   # Azul ONPE (Botones y acentos)
backgroundColor = "#FFFFFF" # Fondo Blanco puro
secondaryBackgroundColor = "#F0F8FF" # Azul muy p√°lido (para las cajas de texto)
textColor = "#262730"      # Texto oscuro
font = "sans serif"