[theme]
base = "dark"               # Activa el modo oscuro base
primaryColor = "#FF4B4B"    # Rojo brillante para botones (Gran contraste sobre negro)
backgroundColor = "#0E1117" # Fondo Negro/Gris muy oscuro (Elegante)
secondaryBackgroundColor = "#262730" # Fondo de los inputs (Gris oscuro)
textColor = "#FAFAFA"       # Texto Blanco Puro
font = "sans serif"